services:
  web:
    image: n0tlu5/kvadminer-rs:latest
    ports:
      - 8080:8080
    environment:
      - REDIS_URL=redis://redis:6379/
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"


volumes:
  cargo-cache:

